services:
  image_processor:
    container_name: image_processor
    image: ${DOCKER_REPOSITORY}/image_processor:${TAG}
    volumes:
      - ${PWD}/images:/app/images
      - ${PWD}/processed:/app/processed
    environment:
      - INPUT_FOLDER=/app/images
      - OUTPUT_FOLDER=/app/processed

  isession:
    container_name: isession
    image: ghcr.io/loxosceles/isession:1.0.0
    command: ['uv', 'run', 'ipython']
    volumes:
      - ./image_processor/pyproject.toml:/app/pyproject.toml
      - ./image_processor/image_processor:/app/image_processor
      - isession_data:/app/.ipython/profile_default
      - ${PWD}/isession/startup:/app/.ipython/profile_default/startup
      - ${PWD}/images:/app/images
      - ${PWD}/processed:/app/processed
    environment:
      - INPUT_FOLDER=/app/images
      - OUTPUT_FOLDER=/app/processed
    stdin_open: true
    tty: true

volumes:
  isession_data:
