[project]
name = "image-processor-utility"
version = "0.1.0"
description = "A package for processing images."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.1.0",
    "tqdm>=4.67.1",
]
