#!/usr/bin/env bash

# Handle help before sourcing to avoid errors
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
        echo "Development management script"
        echo ""
        echo "USAGE: manage.sh <command> options"
        echo ""
        echo "COMMANDS:"
        echo "  api            Start FastAPI backend server"
        echo "  build --no-cache Build and push Docker image to registry"
        echo "  build_local    Build all images locally without pushing"
        echo "  dev            Start API and frontend in development mode"
        echo "  frontend       Start Next.js frontend dev server"
        echo "  help           Show this help message"
        echo "  isession       Start interactive development session"
        echo "  lint           Run ruff linter on all Python code"
        echo "  start          Start API and frontend in production mode"
        echo "  stop           Stop all running servers"
        echo "  test           Run pytest suite with volume mounting"
        echo "  test-api       Run API pytest tests"
        echo "  image_processor Run image processor with arguments"
        echo "  package        Build and install package locally"
        echo ""
        echo "EXAMPLES:"
        echo "  manage.sh help"
        echo "  manage.sh isession"
        echo "  manage.sh test"
        echo "  manage.sh api"
        echo "  manage.sh dev"
        echo "  manage.sh image_processor images/ --output processed/ --task resize"
        exit 0
fi


# Global variables
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/commands.sh"

# Created by argbash-init v2.11.0
# ARG_POSITIONAL_SINGLE([command])
# ARG_LEFTOVERS([args])
# ARG_DEFAULTS_POS([])
# ARG_HELP([Development management script for image processor])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_command=
_arg_leftovers=()
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "Development management script for image processor"
	printf 'Usage: %s [-h|--help] <command> ... \n' "$0"
	printf '\t%s\n' "... : args"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'command'"
	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_command "
	_our_args=$((${#_positionals[@]} - 1))
	for ((ii = 0; ii < _our_args; ii++))
	do
		_positional_names="$_positional_names _arg_leftovers[$((ii + 0))]"
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# Command routing
case "$_arg_command" in
    "build")
        if [ "${_arg_leftovers[0]}" == "--no-cache" ]; then
            cmd_build_and_push "--no-cache"
        else
            cmd_build_and_push
        fi
        ;;
    "build_local") cmd_build_local ;;
    "help")
        echo "Development management script"
        echo ""
        echo "USAGE: manage.sh <command> options"
        echo ""
        echo "COMMANDS:"
        echo "  api            Start FastAPI backend server"
        echo "  build --no-cache Build and push Docker image to registry"
        echo "  build_local    Build all images locally without pushing"
        echo "  dev            Start API and frontend in development mode"
        echo "  frontend       Start Next.js frontend dev server"
        echo "  help           Show this help message"
        echo "  isession       Start interactive development session"
        echo "  lint           Run ruff linter on all Python code"
        echo "  start          Start API and frontend in production mode"
        echo "  stop           Stop all running servers"
        echo "  test           Run pytest suite with volume mounting"
        echo "  test-api       Run API pytest tests"
        echo "  image_processor Run image processor with arguments"
        echo "  package        Build and install package locally"
        echo ""
        echo "EXAMPLES:"
        echo "  manage.sh help"
        echo "  manage.sh isession"
        echo "  manage.sh test"
        echo "  manage.sh image_processor images/ --output processed/ --task resize"
        echo "  manage.sh image_processor images/ --output processed/ --task resize --format webp --quality 80"
        exit 0
        ;;
    "isession") cmd_isession ;;
    "test") cmd_run_tests ;;
    "image_processor") cmd_run_image_processor "${_arg_leftovers[@]}" ;;
    "package") cmd_build_package ;;
    "api") cmd_api ;;
    "frontend") cmd_frontend ;;
    "dev") cmd_dev ;;
    "start") cmd_start ;;
    "stop") cmd_stop ;;
    "lint") cmd_lint ;;
    "test-api") cmd_test_api ;;
    *)
        echo "Unknown command: $_arg_command"
        echo "Run 'manage.sh help' for usage"
        exit 1
        ;;
esac
# ] <-- needed because of Argbash
