#!/bin/sh
# Post-create script for Python devcontainer

set -e

WORKSPACE_ROOT="${WORKSPACE_ROOT:-$PWD}"
SSH_CONTEXT="${SSH_CONTEXT:-default}"
CHEZMOI_DOTFILES_REPOSITORY="${CHEZMOI_DOTFILES_REPOSITORY:-git@github.com:/${GITHUB_USERNAME}/devcontainer-dotfiles}"

# SSH Setup
echo "Setting up SSH configuration..."
if [ -d "$HOME/.ssh" ]; then
  sudo chown -R "$USER":"$USER" "$HOME/.ssh"
fi

cat >"$HOME/.ssh/config" <<EOF
# ===== AUTOGENERATED =====
Include $HOME/.ssh/contexts/$SSH_CONTEXT/config
Host *
  IdentitiesOnly yes
  ServerAliveInterval 60
EOF
echo "✓ SSH configuration complete"

# Chezmoi Setup
echo "Setting up chezmoi configuration..."
mkdir -p "$HOME/.config/chezmoi"
if [ -f "/usr/src/chezmoi.toml" ]; then
  sudo mv /usr/src/chezmoi.toml "$HOME/.config/chezmoi/chezmoi.toml"
  sudo chown -R "$USER":"$USER" "$HOME/.config/chezmoi"
fi

# Dotfiles Setup
echo "Setting up dotfiles..."
if [ -n "$GITHUB_USERNAME" ]; then
  chezmoi init --apply "${CHEZMOI_DOTFILES_REPOSITORY}" || echo "Warning: Failed to initialize dotfiles"
fi

# ZSH Configuration (mounted via bind mount at ~/.config/zsh)
echo "Setting up ZSH configuration..."
[ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/.zshrc.bak"
if [ -f "$HOME/.config/zsh/.zshrc" ]; then
  ln -sf "$HOME/.config/zsh/.zshrc" "$HOME/.zshrc"
fi

# AI Agent Templates Setup
echo "Setting up AI agent templates..."
AGENT_SOURCE_DIR="${WORKSPACE_ROOT}/docs/ai-dev-rules/agents"
if [ -d "$AGENT_SOURCE_DIR" ]; then
  agent_count=$(find "$AGENT_SOURCE_DIR" -maxdepth 1 -name "*.agent.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  if [ "$agent_count" -gt 0 ]; then
    for target_dir in "${WORKSPACE_ROOT}/.github/agents" "${WORKSPACE_ROOT}/.amazonq/agents"; do
      mkdir -p "$target_dir"
      for agent_file in "$AGENT_SOURCE_DIR"/*.agent.md; do
        [ -f "$agent_file" ] && ln -sf "$agent_file" "$target_dir/"
      done
    done
    echo "✓ Symlinked $agent_count agent template(s)"
  fi
fi

echo "✓ Devcontainer setup complete!"
