#!/bin/sh

# Since we mounted the SSH context in the Dockerfile as root, we need to change ownership
sudo chown -R "$USER":"$USER" "$HOME/.ssh"

# Create SSH config which includes the context-specific SSH config
cat >"$HOME/.ssh/config" <<EOF
# ===== AUTOGENERATED =====
Include $HOME/.ssh/contexts/$SSH_CONTEXT/config
Host *
  IdentitiesOnly yes
  ServerAliveInterval 60
EOF

# Create the chezmoi config directory
mkdir -p "$HOME"/.config/chezmoi
# In the Dockerfile we copied the config file to /usr/src
sudo mv /usr/src/chezmoi.toml "$HOME"/.config/chezmoi/chezmoi.toml
sudo chown -R "$USER":"$USER" "$HOME"/.config/chezmoi

# Setup container dotfiles
echo "Setting up dotfiles..."
CHEZMOI_DOTFILES_REPOSITORY="git@github.com:/${GITHUB_USERNAME}/devcontainer-dotfiles"
chezmoi init --apply "${CHEZMOI_DOTFILES_REPOSITORY}"

### FIXME: We're fist copying the .zshrc file to the home directory via chezmoi,
## but now we're backing it up and linking it to a mounted location.
#
# Enable the mounted zsh configuration which was mounted under $HOME/.config/zsh
mv "$HOME"/.zshrc "$HOME"/.zshrc.bak
ln -s "$HOME"/.config/zsh/.zshrc "$HOME"/.zshrc
