name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd image_processor
          docker build -t image_processor .

      - name: Run tests
        run: |
          docker run --rm \
            -v "$(pwd)/image_processor/tests:/app/tests:ro" \
            -v "$(pwd)/image_processor/image_processor:/app/image_processor:ro" \
            image_processor uv run pytest -v
